 export const bills = [
  {
    "id": 1,
    "biller_code": "BIL099",
    "name": "MTN NIgeria",
    "default_commission": 0.03,
    "date_added": "2018-07-03T00:00:00Z",
    "country": "NG",
    "is_airtime": true,
    "biller_name": "AIRTIME",
    "item_code": "AT099",
    "short_name": "MTN",
    "fee": 0,
    "commission_on_fee": false,
    "label_name": "Mobile Number",
    "amount": 0
  },
  {
    "id": 2,
    "biller_code": "BIL099",
    "name": "GLO Nigeria",
    "default_commission": 0.03,
    "date_added": "2018-07-03T00:00:00Z",
    "country": "NG",
    "is_airtime": true,
    "biller_name": "AIRTIME",
    "item_code": "AT099",
    "short_name": "GLO",
    "fee": 0,
    "commission_on_fee": false,
    "label_name": "Mobile Number",
    "amount": 0
  },
  {
    "id": 3,
    "biller_code": "BIL099",
    "name": "9Mobile",
    "default_commission": 0.03,
    "date_added": "2018-07-03T00:00:00Z",
    "country": "NG",
    "is_airtime": true,
    "biller_name": "AIRTIME",
    "item_code": "AT099",
    "short_name": "9mobile",
    "fee": 0,
    "commission_on_fee": false,
    "label_name": "Mobile Number",
    "amount": 0
  },
  {
    "id": 4,
    "biller_code": "BIL099",
    "name": "Airtel Nigeria",
    "default_commission": 0.03,
    "date_added": "2018-07-03T00:00:00Z",
    "country": "NG",
    "is_airtime": true,
    "biller_name": "AIRTIME",
    "item_code": "AT099",
    "short_name": "Airtel",
    "fee": 0,
    "commission_on_fee": false,
    "label_name": "Mobile Number",
    "amount": 0
  },
  {
    "id": 365,
    "biller_code": "BIL108",
    "name": "MTN 200 MB DATA BUNDLE",
    "default_commission": 0.03,
    "date_added": "2020-02-11T11:16:42.727Z",
    "country": "NG",
    "is_airtime": false,
    "biller_name": "MTN 200 MB DATA BUNDLE",
    "item_code": "MD142",
    "short_name": "MTN 200 MB DATA BUNDLE",
    "fee": 0,
    "commission_on_fee": false,
    "label_name": "Mobile Number",
    "amount": 200
  },
  {
    "id": 366,
    "biller_code": "BIL108",
    "name": "MTN 750MB data top-up service",
    "default_commission": 0.03,
    "date_added": "2020-02-11T11:16:42.727Z",
    "country": "NG",
    "is_airtime": false,
    "biller_name": "MTN 750MB data top-up service",
    "item_code": "MD143",
    "short_name": "MTN 750MB data top-up service",
    "fee": 0,
    "commission_on_fee": false,
    "label_name": "Mobile Number",
    "amount": 500
  },
  {
    "id": 367,
    "biller_code": "BIL108",
    "name": "MTN 1.5 GB DATA BUNDLE",
    "default_commission": 0.03,
    "date_added": "2020-02-11T11:16:42.727Z",
    "country": "NG",
    "is_airtime": false,
    "biller_name": "MTN 1.5 GB DATA BUNDLE",
    "item_code": "MD144",
    "short_name": "MTN 1.5 GB DATA BUNDLE",
    "fee": 0,
    "commission_on_fee": false,
    "label_name": "Mobile Number",
    "amount": 1000
  },
  {
    "id": 368,
    "biller_code": "BIL108",
    "name": "MTN 4.5 GB DATA BUNDLE",
    "default_commission": 0.03,
    "date_added": "2020-02-11T11:16:42.727Z",
    "country": "NG",
    "is_airtime": false,
    "biller_name": "MTN 4.5 GB DATA BUNDLE",
    "item_code": "MD145",
    "short_name": "MTN 4.5 GB DATA BUNDLE",
    "fee": 0,
    "commission_on_fee": false,
    "label_name": "Mobile Number",
    "amount": 2000
  },
  {
    "id": 369,
    "biller_code": "BIL108",
    "name": "MTN 10 GB DATA BUNDLE",
    "default_commission": 0.03,
    "date_added": "2020-02-11T11:16:42.727Z",
    "country": "NG",
    "is_airtime": false,
    "biller_name": "MTN 10 GB DATA BUNDLE",
    "item_code": "MD255",
    "short_name": "MTN 10 GB DATA BUNDLE",
    "fee": 0,
    "commission_on_fee": false,
    "label_name": "Mobile Number",
    "amount": 3500
  },
  {
    "id": 370,
    "biller_code": "BIL108",
    "name": "MTN 15 GB DATA BUNDLE",
    "default_commission": 0.03,
    "date_added": "2020-02-11T11:16:42.727Z",
    "country": "NG",
    "is_airtime": false,
    "biller_name": "MTN 15 GB DATA BUNDLE",
    "item_code": "MD256",
    "short_name": "MTN 15 GB DATA BUNDLE",
    "fee": 0,
    "commission_on_fee": false,
    "label_name": "Mobile Number",
    "amount": 5000
  },
  {
    "id": 371,
    "biller_code": "BIL108",
    "name": "MTN 40 GB DATA BUNDLE",
    "default_commission": 0.03,
    "date_added": "2020-02-11T11:16:42.727Z",
    "country": "NG",
    "is_airtime": false,
    "biller_name": "MTN 40 GB DATA BUNDLE",
    "item_code": "MD257",
    "short_name": "MTN 40 GB DATA BUNDLE",
    "fee": 0,
    "commission_on_fee": false,
    "label_name": "Mobile Number",
    "amount": 10000
  },
  {
    "id": 372,
    "biller_code": "BIL108",
    "name": "MTN 75 GB DATA BUNDLE",
    "default_commission": 0.03,
    "date_added": "2020-02-11T11:16:42.727Z",
    "country": "NG",
    "is_airtime": false,
    "biller_name": "MTN 75 GB DATA BUNDLE",
    "item_code": "MD258",
    "short_name": "MTN 75 GB DATA BUNDLE",
    "fee": 0,
    "commission_on_fee": false,
    "label_name": "Mobile Number",
    "amount": 20000
  },
  {
    "id": 373,
    "biller_code": "BIL108",
    "name": "MTN 120 GB DATA BUNDLE",
    "default_commission": 0.03,
    "date_added": "2020-02-11T11:16:42.727Z",
    "country": "NG",
    "is_airtime": false,
    "biller_name": "MTN 120 GB DATA BUNDLE",
    "item_code": "MD259",
    "short_name": "MTN 120 GB DATA BUNDLE",
    "fee": 0,
    "commission_on_fee": false,
    "label_name": "Mobile Number",
    "amount": 30000
  },
  {
    "id": 374,
    "biller_code": "BIL109",
    "name": "GLO 35 MB data bundle",
    "default_commission": 0.03,
    "date_added": "2020-02-11T11:16:42.727Z",
    "country": "NG",
    "is_airtime": false,
    "biller_name": "GLO 35 MB data bundle",
    "item_code": "MD146",
    "short_name": "GLO 35 MB data bundle",
    "fee": 0,
    "commission_on_fee": false,
    "label_name": "Mobile Number",
    "amount": 100
  },
  {
    "id": 375,
    "biller_code": "BIL109",
    "name": "GLO 100 MB DATA BUNDLE",
    "default_commission": 0.03,
    "date_added": "2020-02-11T11:16:42.727Z",
    "country": "NG",
    "is_airtime": false,
    "biller_name": "GLO 100 MB DATA BUNDLE",
    "item_code": "MD147",
    "short_name": "GLO 100 MB DATA BUNDLE",
    "fee": 0,
    "commission_on_fee": false,
    "label_name": "Mobile Number",
    "amount": 200
  },
  {
    "id": 376,
    "biller_code": "BIL109",
    "name": "GLO 920 MB DATA BUNDLE",
    "default_commission": 0.03,
    "date_added": "2020-02-11T11:16:42.727Z",
    "country": "NG",
    "is_airtime": false,
    "biller_name": "GLO 920 MB DATA BUNDLE",
    "item_code": "MD148",
    "short_name": "GLO 920 MB DATA BUNDLE",
    "fee": 0,
    "commission_on_fee": false,
    "label_name": "Mobile Number",
    "amount": 500
  },
  {
    "id": 377,
    "biller_code": "BIL109",
    "name": "GLO 1.8GB data purchase",
    "default_commission": 0.03,
    "date_added": "2020-02-11T11:16:42.727Z",
    "country": "NG",
    "is_airtime": false,
    "biller_name": "GLO 1.8GB data purchase",
    "item_code": "MD149",
    "short_name": "GLO 1.8GB data purchase",
    "fee": 0,
    "commission_on_fee": false,
    "label_name": "Mobile Number",
    "amount": 1000
  },
  {
    "id": 378,
    "biller_code": "BIL109",
    "name": "GLO 4.5GB data bundle",
    "default_commission": 0.03,
    "date_added": "2020-02-11T11:16:42.727Z",
    "country": "NG",
    "is_airtime": false,
    "biller_name": "GLO 4.5GB data bundle",
    "item_code": "MD150",
    "short_name": "GLO 4.5GB data bundle",
    "fee": 0,
    "commission_on_fee": false,
    "label_name": "Mobile Number",
    "amount": 2000
  },
  {
    "id": 379,
    "biller_code": "BIL109",
    "name": "GLO 7.2GB data bundle",
    "default_commission": 0.03,
    "date_added": "2020-02-11T11:16:42.727Z",
    "country": "NG",
    "is_airtime": false,
    "biller_name": "GLO 7.2GB data bundle",
    "item_code": "MD151",
    "short_name": "GLO 7.2GB data bundle",
    "fee": 0,
    "commission_on_fee": false,
    "label_name": "Mobile Number",
    "amount": 2500
  },
  {
    "id": 380,
    "biller_code": "BIL109",
    "name": "GLO 8.75GB DATA BUNDLE",
    "default_commission": 0.03,
    "date_added": "2020-02-11T11:16:42.727Z",
    "country": "NG",
    "is_airtime": false,
    "biller_name": "GLO 8.75GB DATA BUNDLE",
    "item_code": "MD366",
    "short_name": "GLO 8.75GB DATA BUNDLE",
    "fee": 0,
    "commission_on_fee": false,
    "label_name": "Mobile Number",
    "amount": 3000
  },
  {
    "id": 381,
    "biller_code": "BIL109",
    "name": "GLO 12.5GB DATA BUNDLE",
    "default_commission": 0.03,
    "date_added": "2020-02-11T11:16:42.727Z",
    "country": "NG",
    "is_airtime": false,
    "biller_name": "GLO 12.5GB DATA BUNDLE",
    "item_code": "MD367",
    "short_name": "GLO 12.5GB DATA BUNDLE",
    "fee": 0,
    "commission_on_fee": false,
    "label_name": "Mobile Number",
    "amount": 4000
  },
  {
    "id": 382,
    "biller_code": "BIL109",
    "name": "GLO 15.6GB DATA BUNDLE",
    "default_commission": 0.03,
    "date_added": "2020-02-11T11:16:42.727Z",
    "country": "NG",
    "is_airtime": false,
    "biller_name": "GLO 15.6GB DATA BUNDLE",
    "item_code": "MD368",
    "short_name": "GLO 15.6GB DATA BUNDLE",
    "fee": 0,
    "commission_on_fee": false,
    "label_name": "Mobile Number",
    "amount": 5000
  },
  {
    "id": 383,
    "biller_code": "BIL109",
    "name": "GLO 25GB DATA BUNDLE",
    "default_commission": 0.03,
    "date_added": "2020-02-11T11:16:42.727Z",
    "country": "NG",
    "is_airtime": false,
    "biller_name": "GLO 25GB DATA BUNDLE",
    "item_code": "MD369",
    "short_name": "GLO 25GB DATA BUNDLE",
    "fee": 0,
    "commission_on_fee": false,
    "label_name": "Mobile Number",
    "amount": 8000
  },
  {
    "id": 384,
    "biller_code": "BIL109",
    "name": "GLO 32.5GB DATA BUNDLE",
    "default_commission": 0.03,
    "date_added": "2020-02-11T11:16:42.727Z",
    "country": "NG",
    "is_airtime": false,
    "biller_name": "GLO 32.5GB DATA BUNDLE",
    "item_code": "MD370",
    "short_name": "GLO 32.5GB DATA BUNDLE",
    "fee": 0,
    "commission_on_fee": false,
    "label_name": "Mobile Number",
    "amount": 10000
  },
  {
    "id": 385,
    "biller_code": "BIL109",
    "name": "GLO 52.5GB DATA BUNDLE",
    "default_commission": 0.03,
    "date_added": "2020-02-11T11:16:42.727Z",
    "country": "NG",
    "is_airtime": false,
    "biller_name": "GLO 52.5GB DATA BUNDLE",
    "item_code": "MD371",
    "short_name": "GLO 52.5GB DATA BUNDLE",
    "fee": 0,
    "commission_on_fee": false,
    "label_name": "Mobile Number",
    "amount": 15000
  },
  {
    "id": 386,
    "biller_code": "BIL109",
    "name": "GLO 62.5GB DATA BUNDLE",
    "default_commission": 0.03,
    "date_added": "2020-02-11T11:16:42.727Z",
    "country": "NG",
    "is_airtime": false,
    "biller_name": "GLO 62.5GB DATA BUNDLE",
    "item_code": "MD372",
    "short_name": "GLO 62.5GB DATA BUNDLE",
    "fee": 0,
    "commission_on_fee": false,
    "label_name": "Mobile Number",
    "amount": 18000
  },
  {
    "id": 387,
    "biller_code": "BIL110",
    "name": "AIRTEL 40 MB data bundle",
    "default_commission": 0.03,
    "date_added": "2020-02-11T11:16:42.727Z",
    "country": "NG",
    "is_airtime": false,
    "biller_name": "AIRTEL 40 MB data bundle",
    "item_code": "MD135",
    "short_name": "AIRTEL 40 MB data bundle",
    "fee": 0,
    "commission_on_fee": false,
    "label_name": "Mobile Number",
    "amount": 50
  },
  {
    "id": 388,
    "biller_code": "BIL110",
    "name": "AIRTEL 100 MB data bundle",
    "default_commission": 0.03,
    "date_added": "2020-02-11T11:16:42.727Z",
    "country": "NG",
    "is_airtime": false,
    "biller_name": "AIRTEL 100 MB data bundle",
    "item_code": "MD136",
    "short_name": "AIRTEL 100 MB data bundle",
    "fee": 0,
    "commission_on_fee": false,
    "label_name": "Mobile Number",
    "amount": 100
  },
  {
    "id": 389,
    "biller_code": "BIL110",
    "name": "AIRTEL 200 MB data bundle",
    "default_commission": 0.03,
    "date_added": "2020-02-11T11:16:42.727Z",
    "country": "NG",
    "is_airtime": false,
    "biller_name": "AIRTEL 200 MB data bundle",
    "item_code": "MD137",
    "short_name": "AIRTEL 200 MB data bundle",
    "fee": 0,
    "commission_on_fee": false,
    "label_name": "Mobile Number",
    "amount": 200
  },
  {
    "id": 390,
    "biller_code": "BIL110",
    "name": "AIRTEL 350 MB data bundle",
    "default_commission": 0.03,
    "date_added": "2020-02-11T11:16:42.727Z",
    "country": "NG",
    "is_airtime": false,
    "biller_name": "AIRTEL 350 MB data bundle",
    "item_code": "MD138",
    "short_name": "AIRTEL 350 MB data bundle",
    "fee": 0,
    "commission_on_fee": false,
    "label_name": "Mobile Number",
    "amount": 300
  },
  {
    "id": 391,
    "biller_code": "BIL110",
    "name": "AIRTEL 750 MB data bundle",
    "default_commission": 0.03,
    "date_added": "2020-02-11T11:16:42.727Z",
    "country": "NG",
    "is_airtime": false,
    "biller_name": "AIRTEL 750 MB data bundle",
    "item_code": "MD139",
    "short_name": "AIRTEL 750 MB data bundle",
    "fee": 0,
    "commission_on_fee": false,
    "label_name": "Mobile Number",
    "amount": 500
  },
  {
    "id": 392,
    "biller_code": "BIL110",
    "name": "AIRTEL 1.5GB data bundle",
    "default_commission": 0.03,
    "date_added": "2020-02-11T11:16:42.727Z",
    "country": "NG",
    "is_airtime": false,
    "biller_name": "AIRTEL 1.5GB data bundle",
    "item_code": "MD140",
    "short_name": "AIRTEL 1.5GB data bundle",
    "fee": 0,
    "commission_on_fee": false,
    "label_name": "Mobile Number",
    "amount": 1000
  },
  {
    "id": 393,
    "biller_code": "BIL110",
    "name": "AIRTEL 3GB Data Bundle",
    "default_commission": 0.03,
    "date_added": "2020-02-11T11:16:42.727Z",
    "country": "NG",
    "is_airtime": false,
    "biller_name": "AIRTEL 3GB Data Bundle",
    "item_code": "MD373",
    "short_name": "AIRTEL 3GB Data Bundle",
    "fee": 0,
    "commission_on_fee": false,
    "label_name": "Mobile Number",
    "amount": 1500
  },
  {
    "id": 394,
    "biller_code": "BIL110",
    "name": "AIRTEL 6GB Data Bundle",
    "default_commission": 0.03,
    "date_added": "2020-02-11T11:16:42.727Z",
    "country": "NG",
    "is_airtime": false,
    "biller_name": "AIRTEL 6GB Data Bundle",
    "item_code": "MD374",
    "short_name": "AIRTEL 6GB Data Bundle",
    "fee": 0,
    "commission_on_fee": false,
    "label_name": "Mobile Number",
    "amount": 2500
  },
  {
    "id": 395,
    "biller_code": "BIL110",
    "name": "AIRTEL 8GB Data Bundle",
    "default_commission": 0.03,
    "date_added": "2020-02-11T11:16:42.727Z",
    "country": "NG",
    "is_airtime": false,
    "biller_name": "AIRTEL 8GB Data Bundle",
    "item_code": "MD375",
    "short_name": "AIRTEL 8GB Data Bundle",
    "fee": 0,
    "commission_on_fee": false,
    "label_name": "Mobile Number",
    "amount": 3000
  },
  {
    "id": 396,
    "biller_code": "BIL110",
    "name": "AIRTEL 11GB Data Bundle",
    "default_commission": 0.03,
    "date_added": "2020-02-11T11:16:42.727Z",
    "country": "NG",
    "is_airtime": false,
    "biller_name": "AIRTEL 11GB Data Bundle",
    "item_code": "MD376",
    "short_name": "AIRTEL 11GB Data Bundle",
    "fee": 0,
    "commission_on_fee": false,
    "label_name": "Mobile Number",
    "amount": 4000
  },
  {
    "id": 397,
    "biller_code": "BIL110",
    "name": "AIRTEL 15GB Data Bundle",
    "default_commission": 0.03,
    "date_added": "2020-02-11T11:16:42.727Z",
    "country": "NG",
    "is_airtime": false,
    "biller_name": "AIRTEL 15GB Data Bundle",
    "item_code": "MD377",
    "short_name": "AIRTEL 15GB Data Bundle",
    "fee": 0,
    "commission_on_fee": false,
    "label_name": "Mobile Number",
    "amount": 5000
  },
  {
    "id": 398,
    "biller_code": "BIL110",
    "name": "AIRTEL 40GB Data Bundle",
    "default_commission": 0.03,
    "date_added": "2020-02-11T11:16:42.727Z",
    "country": "NG",
    "is_airtime": false,
    "biller_name": "AIRTEL 40GB Data Bundle",
    "item_code": "MD378",
    "short_name": "AIRTEL 40GB Data Bundle",
    "fee": 0,
    "commission_on_fee": false,
    "label_name": "Mobile Number",
    "amount": 10000
  },
  {
    "id": 399,
    "biller_code": "BIL110",
    "name": "AIRTEL 75GB Data Bundle",
    "default_commission": 0.03,
    "date_added": "2020-02-11T11:16:42.727Z",
    "country": "NG",
    "is_airtime": false,
    "biller_name": "AIRTEL 75GB Data Bundle",
    "item_code": "MD379",
    "short_name": "AIRTEL 75GB Data Bundle",
    "fee": 0,
    "commission_on_fee": false,
    "label_name": "Mobile Number",
    "amount": 15000
  },
  {
    "id": 402,
    "biller_code": "BIL111",
    "name": "9MOBILE 1.5GB data bundle",
    "default_commission": 0.03,
    "date_added": "2020-02-11T11:16:42.727Z",
    "country": "NG",
    "is_airtime": false,
    "biller_name": "9MOBILE 1.5GB data bundle",
    "item_code": "MD154",
    "short_name": "9MOBILE 1.5GB data bundle",
    "fee": 0,
    "commission_on_fee": false,
    "label_name": "Mobile Number",
    "amount": 1000
  },
  {
    "id": 403,
    "biller_code": "BIL111",
    "name": "9MOBILE 4.5GB data bundle",
    "default_commission": 0.03,
    "date_added": "2020-02-11T11:16:42.727Z",
    "country": "NG",
    "is_airtime": false,
    "biller_name": "9MOBILE 4.5GB data bundle",
    "item_code": "MD155",
    "short_name": "9MOBILE 4.5GB data bundle",
    "fee": 0,
    "commission_on_fee": false,
    "label_name": "Mobile Number",
    "amount": 2000
  },
  {
    "id": 404,
    "biller_code": "BIL111",
    "name": "9MOBILE 4GB data bundle",
    "default_commission": 0.03,
    "date_added": "2020-02-11T11:16:42.727Z",
    "country": "NG",
    "is_airtime": false,
    "biller_name": "9MOBILE 4GB data bundle",
    "item_code": "MD156",
    "short_name": "9MOBILE 4GB data bundle",
    "fee": 0,
    "commission_on_fee": false,
    "label_name": "Mobile Number",
    "amount": 3000
  },
  {
    "id": 405,
    "biller_code": "BIL111",
    "name": "9MOBILE 11.5GB data bundle ",
    "default_commission": 0.03,
    "date_added": "2020-02-11T11:16:42.727Z",
    "country": "NG",
    "is_airtime": false,
    "biller_name": "9MOBILE 11.5GB data bundle ",
    "item_code": "MD361",
    "short_name": "9MOBILE 11.5GB data bundle ",
    "fee": 0,
    "commission_on_fee": false,
    "label_name": "Mobile Number",
    "amount": 4000
  },
  {
    "id": 406,
    "biller_code": "BIL111",
    "name": "9MOBILE 15GB data bundle ",
    "default_commission": 0.03,
    "date_added": "2020-02-11T11:16:42.727Z",
    "country": "NG",
    "is_airtime": false,
    "biller_name": "9MOBILE 15GB data bundle ",
    "item_code": "MD362",
    "short_name": "9MOBILE 15GB data bundle ",
    "fee": 0,
    "commission_on_fee": false,
    "label_name": "Mobile Number",
    "amount": 5000
  },
  {
    "id": 407,
    "biller_code": "BIL111",
    "name": "9MOBILE 27.5GB data bundle ",
    "default_commission": 0.03,
    "date_added": "2020-02-11T11:16:42.727Z",
    "country": "NG",
    "is_airtime": false,
    "biller_name": "9MOBILE 27.5GB data bundle ",
    "item_code": "MD363",
    "short_name": "9MOBILE 27.5GB data bundle ",
    "fee": 0,
    "commission_on_fee": false,
    "label_name": "Mobile Number",
    "amount": 18000
  },
  {
    "id": 408,
    "biller_code": "BIL111",
    "name": "9MOBILE 30GB data bundle ",
    "default_commission": 0.03,
    "date_added": "2020-02-11T11:16:42.727Z",
    "country": "NG",
    "is_airtime": false,
    "biller_name": "9MOBILE 30GB data bundle ",
    "item_code": "MD364",
    "short_name": "9MOBILE 30GB data bundle ",
    "fee": 0,
    "commission_on_fee": false,
    "label_name": "Mobile Number",
    "amount": 27500
  },
  {
    "id": 409,
    "biller_code": "BIL111",
    "name": "9MOBILE 60GB data bundle ",
    "default_commission": 0.03,
    "date_added": "2020-02-11T11:16:42.727Z",
    "country": "NG",
    "is_airtime": false,
    "biller_name": "9MOBILE 60GB data bundle ",
    "item_code": "MD365",
    "short_name": "9MOBILE 60GB data bundle ",
    "fee": 0,
    "commission_on_fee": false,
    "label_name": "Mobile Number",
    "amount": 55000
  },
  {
    "id": 16871,
    "biller_code": "BIL111",
    "name": "9MOBILE 650 MB data bundle",
    "default_commission": 0.03,
    "date_added": "2020-05-30T00:00:00Z",
    "country": "NG",
    "is_airtime": false,
    "biller_name": "9MOBILE 650 MB data bundle",
    "item_code": "MD152",
    "short_name": "9MOBILE 650 MB data bundle",
    "fee": 0,
    "commission_on_fee": false,
    "label_name": "Mobile Number",
    "amount": 200
  },
  {
    "id": 16872,
    "biller_code": "BIL108",
    "name": "MTN 8GB data purchase (1 Month)",
    "default_commission": 0.03,
    "date_added": "2020-02-11T11:16:42.727Z",
    "country": "NG",
    "is_airtime": false,
    "biller_name": "MTN 8GB data purchase (1 Month)",
    "item_code": "MD506",
    "short_name": "MTN 8GB data purchase (1 Month)",
    "fee": 0,
    "commission_on_fee": false,
    "label_name": "Mobile Number",
    "amount": 3000
  },
  {
    "id": 16873,
    "biller_code": "BIL108",
    "name": "MTN 2.5GB data purchase (2 Days)",
    "default_commission": 0.03,
    "date_added": "2020-05-30T00:00:00Z",
    "country": "NG",
    "is_airtime": false,
    "biller_name": "MTN 2.5GB data purchase (2 Days)",
    "item_code": "MD496",
    "short_name": "MTN 2.5GB data purchase (2 Days)",
    "fee": 0,
    "commission_on_fee": false,
    "label_name": "Mobile Number",
    "amount": 500
  },
  {
    "id": 16874,
    "biller_code": "BIL108",
    "name": "MTN 6GB data purchase (1 Month)",
    "default_commission": 0.03,
    "date_added": "2020-05-30T00:00:00Z",
    "country": "NG",
    "is_airtime": false,
    "biller_name": "MTN 6GB data purchase (1 Month)",
    "item_code": "MD495",
    "short_name": "MTN 6GB data purchase (1 Month)",
    "fee": 0,
    "commission_on_fee": false,
    "label_name": "Mobile Number",
    "amount": 2500
  },
  {
    "id": 16881,
    "biller_code": "BIL108",
    "name": "MTN 100 MB DATA BUNDLE",
    "default_commission": 0.03,
    "date_added": "2020-05-30T00:00:00Z",
    "country": "NG",
    "is_airtime": false,
    "biller_name": "MTN 100 MB DATA BUNDLE",
    "item_code": "MD141",
    "short_name": "MTN 100 MB DATA BUNDLE",
    "fee": 0,
    "commission_on_fee": false,
    "label_name": "Mobile Number",
    "amount": 100
  },
  {
    "id": 16882,
    "biller_code": "BIL108",
    "name": "MTN 350 data purchase (7 days)",
    "default_commission": 0.03,
    "date_added": "2020-05-30T00:00:00Z",
    "country": "NG",
    "is_airtime": false,
    "biller_name": "MTN 350 data purchase (7 days)",
    "item_code": "MD488",
    "short_name": "MTN 350 data purchase (7 days)",
    "fee": 0,
    "commission_on_fee": false,
    "label_name": "Mobile Number",
    "amount": 300
  },
  {
    "id": 16883,
    "biller_code": "BIL108",
    "name": "MTN 1GB data purchase (1 day)",
    "default_commission": 0.03,
    "date_added": "2020-05-30T00:00:00Z",
    "country": "NG",
    "is_airtime": false,
    "biller_name": "MTN 1GB data purchase (1 day)",
    "item_code": "MD489",
    "short_name": "MTN 1GB data purchase (1 day)",
    "fee": 0,
    "commission_on_fee": false,
    "label_name": "Mobile Number",
    "amount": 350
  },
  {
    "id": 16884,
    "biller_code": "BIL108",
    "name": "MTN 750 data purchase (7Days)",
    "default_commission": 0.03,
    "date_added": "2020-05-30T00:00:00Z",
    "country": "NG",
    "is_airtime": false,
    "biller_name": "MTN 750 data purchase (7Days)",
    "item_code": "MD490",
    "short_name": "MTN 750 data purchase (7Days)",
    "fee": 0,
    "commission_on_fee": false,
    "label_name": "Mobile Number",
    "amount": 500
  },
  {
    "id": 16885,
    "biller_code": "BIL108",
    "name": "MTN 3GB data purchase",
    "default_commission": 0.03,
    "date_added": "2020-05-30T00:00:00Z",
    "country": "NG",
    "is_airtime": false,
    "biller_name": "MTN 3GB data purchase",
    "item_code": "MD491",
    "short_name": "MTN 3GB data purchase",
    "fee": 0,
    "commission_on_fee": false,
    "label_name": "Mobile Number",
    "amount": 1500
  },
  {
    "id": 16886,
    "biller_code": "BIL108",
    "name": "MTN 2GB data purchase",
    "default_commission": 0.03,
    "date_added": "2020-05-30T00:00:00Z",
    "country": "NG",
    "is_airtime": false,
    "biller_name": "MTN 2GB data purchase",
    "item_code": "MD492",
    "short_name": "MTN 2GB data purchase",
    "fee": 0,
    "commission_on_fee": false,
    "label_name": "Mobile Number",
    "amount": 1200
  },
  {
    "id": 16887,
    "biller_code": "BIL108",
    "name": "MTN 6GB data purchase (7 days)",
    "default_commission": 0.03,
    "date_added": "2020-05-30T00:00:00Z",
    "country": "NG",
    "is_airtime": false,
    "biller_name": "MTN 6GB data purchase (7 days)",
    "item_code": "MD493",
    "short_name": "MTN 6GB data purchase (7 days)",
    "fee": 0,
    "commission_on_fee": false,
    "label_name": "Mobile Number",
    "amount": 1500
  },
  {
    "id": 16888,
    "biller_code": "BIL108",
    "name": "MTN 1GB data purchase (7 days)",
    "default_commission": 0.03,
    "date_added": "2020-05-30T00:00:00Z",
    "country": "NG",
    "is_airtime": false,
    "biller_name": "MTN 1GB data purchase (7 days)",
    "item_code": "MD494",
    "short_name": "MTN 1GB data purchase (7 days)",
    "fee": 0,
    "commission_on_fee": false,
    "label_name": "Mobile Number",
    "amount": 500
  },
  {
    "id": 267,
    "biller_code": "BIL112",
    "name": "EKO DISCO ELECTRICITY BILLS FOR PREPAID CLIENTS",
    "default_commission": 0.3,
    "date_added": "2020-02-11T11:09:48.087Z",
    "country": "NG",
    "is_airtime": false,
    "biller_name": "EKEDC PREPAID TOPUP",
    "item_code": "UB157",
    "short_name": "EKEDC PREPAID TOPUP",
    "fee": 100,
    "commission_on_fee": true,
    "label_name": "Meter Number",
    "amount": 0
  },
  {
    "id": 268,
    "biller_code": "BIL112",
    "name": "EKO Disco postpaid bills",
    "default_commission": 0.3,
    "date_added": "2020-02-11T11:09:48.087Z",
    "country": "NG",
    "is_airtime": false,
    "biller_name": "EKEDC POSTPAID TOPUP",
    "item_code": "UB158",
    "short_name": "EKEDC POSTPAID TOPUP",
    "fee": 100,
    "commission_on_fee": true,
    "label_name": "Meter Number",
    "amount": 0
  },
  {
    "id": 269,
    "biller_code": "BIL113",
    "name": "IKEDC Prepaid topup",
    "default_commission": 0.3,
    "date_added": "2020-02-11T11:09:48.087Z",
    "country": "NG",
    "is_airtime": false,
    "biller_name": "IKEDC  PREPAID TOP UP",
    "item_code": "UB159",
    "short_name": "IKEDC  PREPAID TOP UP",
    "fee": 100,
    "commission_on_fee": true,
    "label_name": "Meter Number",
    "amount": 0
  },
  {
    "id": 270,
    "biller_code": "BIL113",
    "name": "IKEDC post-paid bill payment",
    "default_commission": 0.3,
    "date_added": "2020-02-11T11:09:48.087Z",
    "country": "NG",
    "is_airtime": false,
    "biller_name": "IKEDC  POSTPAID TOP UP",
    "item_code": "UB160",
    "short_name": "IKEDC  POSTPAID TOP UP",
    "fee": 100,
    "commission_on_fee": true,
    "label_name": "Meter Number",
    "amount": 0
  },
  {
    "id": 271,
    "biller_code": "BIL114",
    "name": "IBADAN DISCO ELECTRICITY PREPAID TOP UP",
    "default_commission": 0.3,
    "date_added": "2020-02-11T11:09:48.087Z",
    "country": "NG",
    "is_airtime": false,
    "biller_name": "IBADAN DISCO ELECTRICITY PREPAID TOP UP",
    "item_code": "UB161",
    "short_name": "IBADAN DISCO ELECTRICITY PREPAID TOP UP",
    "fee": 100,
    "commission_on_fee": true,
    "label_name": "Meter Number",
    "amount": 0
  },
  {
    "id": 272,
    "biller_code": "BIL114",
    "name": "IBADAN DISCO ELECTRICITY POSTPAID TOPUP",
    "default_commission": 0.3,
    "date_added": "2020-02-11T11:09:48.087Z",
    "country": "NG",
    "is_airtime": false,
    "biller_name": "IBADAN DISCO ELECTRICITY POSTPAID TOPUP",
    "item_code": "UB162",
    "short_name": "IBADAN DISCO ELECTRICITY POSTPAID TOPUP",
    "fee": 100,
    "commission_on_fee": true,
    "label_name": "Meter Number",
    "amount": 0
  },
  {
    "id": 273,
    "biller_code": "BIL115",
    "name": "ENUGU DISCO ELECTRIC BILLS PREPAID TOPUP",
    "default_commission": 0.3,
    "date_added": "2020-02-11T11:09:48.087Z",
    "country": "NG",
    "is_airtime": false,
    "biller_name": "ENUGU DISCO ELECTRIC BILLS PREPAID TOPUP",
    "item_code": "UB163",
    "short_name": "ENUGU DISCO ELECTRIC BILLS PREPAID TOPUP",
    "fee": 100,
    "commission_on_fee": true,
    "label_name": "Meter Number",
    "amount": 0
  },
  {
    "id": 274,
    "biller_code": "BIL115",
    "name": "ENUGU DISCO ELECTRIC BILLS POSTPAID TOPUP",
    "default_commission": 0.3,
    "date_added": "2020-02-11T11:09:48.087Z",
    "country": "NG",
    "is_airtime": false,
    "biller_name": "ENUGU DISCO ELECTRIC BILLS POSTPAID TOPUP",
    "item_code": "UB164",
    "short_name": "ENUGU DISCO ELECTRIC BILLS POSTPAID TOPUP",
    "fee": 100,
    "commission_on_fee": true,
    "label_name": "Meter Number",
    "amount": 0
  },
  {
    "id": 275,
    "biller_code": "BIL116",
    "name": "PHC DISCO POSTPAID TOPUP",
    "default_commission": 0.3,
    "date_added": "2020-02-11T11:09:48.087Z",
    "country": "NG",
    "is_airtime": false,
    "biller_name": "PHC DISCO POSTPAID TOPUP",
    "item_code": "UB165",
    "short_name": "PHC DISCO POSTPAID TOPUP",
    "fee": 100,
    "commission_on_fee": true,
    "label_name": "Meter Number",
    "amount": 0
  },
  {
    "id": 276,
    "biller_code": "BIL117",
    "name": "BENIN DISCO POSTPAID TOPUP",
    "default_commission": 0.3,
    "date_added": "2020-02-11T11:09:48.087Z",
    "country": "NG",
    "is_airtime": false,
    "biller_name": "BENIN DISCO POSTPAID TOPUP",
    "item_code": "UB166",
    "short_name": "BENIN DISCO POSTPAID TOPUP",
    "fee": 100,
    "commission_on_fee": true,
    "label_name": "Meter Number",
    "amount": 0
  },
  {
    "id": 277,
    "biller_code": "BIL117",
    "name": "BENIN DISCO PREPAID TOPUP",
    "default_commission": 0.3,
    "date_added": "2020-02-11T11:09:48.087Z",
    "country": "NG",
    "is_airtime": false,
    "biller_name": "BENIN DISCO PREPAID TOPUP",
    "item_code": "UB167",
    "short_name": "BENIN DISCO PREPAID TOPUP",
    "fee": 100,
    "commission_on_fee": true,
    "label_name": "Meter Number",
    "amount": 0
  },
  {
    "id": 278,
    "biller_code": "BIL118",
    "name": "YOLA DISCO TOPUP",
    "default_commission": 0.3,
    "date_added": "2020-02-11T11:09:48.087Z",
    "country": "NG",
    "is_airtime": false,
    "biller_name": "YOLA DISCO TOPUP",
    "item_code": "UB168",
    "short_name": "YOLA DISCO TOPUP",
    "fee": 100,
    "commission_on_fee": true,
    "label_name": "Meter Number",
    "amount": 0
  },
  {
    "id": 279,
    "biller_code": "BIL120",
    "name": "KANO DISCO PREPAID TOPUP",
    "default_commission": 0.3,
    "date_added": "2020-02-11T11:09:48.087Z",
    "country": "NG",
    "is_airtime": false,
    "biller_name": "KANO DISCO PREPAID TOPUP",
    "item_code": "UB169",
    "short_name": "KANO DISCO PREPAID TOPUP",
    "fee": 100,
    "commission_on_fee": true,
    "label_name": "Meter Number",
    "amount": 0
  },
  {
    "id": 280,
    "biller_code": "BIL120",
    "name": "KANO DISCO POSTPAID TOPUP",
    "default_commission": 0.3,
    "date_added": "2020-02-11T11:09:48.087Z",
    "country": "NG",
    "is_airtime": false,
    "biller_name": "KANO DISCO POSTPAID TOPUP",
    "item_code": "UB170",
    "short_name": "KANO DISCO POSTPAID TOPUP",
    "fee": 100,
    "commission_on_fee": true,
    "label_name": "Meter Number",
    "amount": 0
  },
  {
    "id": 287,
    "biller_code": "BIL121",
    "name": "DSTV COMPACT",
    "default_commission": 0.3,
    "date_added": "2020-02-11T11:13:29.62Z",
    "country": "NG",
    "is_airtime": false,
    "biller_name": "DSTV COMPACT",
    "item_code": "CB177",
    "short_name": "DSTV COMPACT",
    "fee": 100,
    "commission_on_fee": true,
    "label_name": "SmartCard Number",
    "amount": 7900
  },
  {
    "id": 288,
    "biller_code": "BIL121",
    "name": "DSTV COMPACT + HD",
    "default_commission": 0.3,
    "date_added": "2020-02-11T11:13:29.62Z",
    "country": "NG",
    "is_airtime": false,
    "biller_name": "DSTV COMPACT + HD",
    "item_code": "CB178",
    "short_name": "DSTV COMPACT + HD",
    "fee": 100,
    "commission_on_fee": true,
    "label_name": "SmartCard Number",
    "amount": 10400
  },
  {
    "id": 289,
    "biller_code": "BIL121",
    "name": "DSTV COMPACT PLUS",
    "default_commission": 0.3,
    "date_added": "2020-02-11T11:13:29.62Z",
    "country": "NG",
    "is_airtime": false,
    "biller_name": "DSTV COMPACT PLUS",
    "item_code": "CB179",
    "short_name": "DSTV COMPACT PLUS",
    "fee": 100,
    "commission_on_fee": true,
    "label_name": "SmartCard Number",
    "amount": 12400
  },
  {
    "id": 290,
    "biller_code": "BIL121",
    "name": "DSTV COMPACT PLUS + ASIA",
    "default_commission": 0.3,
    "date_added": "2020-02-11T11:13:29.62Z",
    "country": "NG",
    "is_airtime": false,
    "biller_name": "DSTV COMPACT PLUS + ASIA",
    "item_code": "CB180",
    "short_name": "DSTV COMPACT PLUS + ASIA",
    "fee": 100,
    "commission_on_fee": true,
    "label_name": "SmartCard Number",
    "amount": 18600
  },
  {
    "id": 291,
    "biller_code": "BIL121",
    "name": "DSTV COMPACT PLUS + HD",
    "default_commission": 0.3,
    "date_added": "2020-02-11T11:13:29.62Z",
    "country": "NG",
    "is_airtime": false,
    "biller_name": "DSTV COMPACT PLUS + HD",
    "item_code": "CB181",
    "short_name": "DSTV COMPACT PLUS + HD",
    "fee": 100,
    "commission_on_fee": true,
    "label_name": "SmartCard Number",
    "amount": 14900
  },
  {
    "id": 292,
    "biller_code": "BIL121",
    "name": "DSTV PREMIUM",
    "default_commission": 0.3,
    "date_added": "2020-02-11T11:13:29.62Z",
    "country": "NG",
    "is_airtime": false,
    "biller_name": "DSTV PREMIUM",
    "item_code": "CB182",
    "short_name": "DSTV PREMIUM",
    "fee": 100,
    "commission_on_fee": true,
    "label_name": "SmartCard Number",
    "amount": 18400
  },
  {
    "id": 293,
    "biller_code": "BIL121",
    "name": "DSTV PREMIUM ASIA",
    "default_commission": 0.3,
    "date_added": "2020-02-11T11:13:29.62Z",
    "country": "NG",
    "is_airtime": false,
    "biller_name": "DSTV PREMIUM ASIA",
    "item_code": "CB183",
    "short_name": "DSTV PREMIUM ASIA",
    "fee": 100,
    "commission_on_fee": true,
    "label_name": "SmartCard Number",
    "amount": 17700
  },
  {
    "id": 294,
    "biller_code": "BIL121",
    "name": "DSTV PREMIUM + HD",
    "default_commission": 0.3,
    "date_added": "2020-02-11T11:13:29.62Z",
    "country": "NG",
    "is_airtime": false,
    "biller_name": "DSTV PREMIUM + HD",
    "item_code": "CB184",
    "short_name": "DSTV PREMIUM + HD",
    "fee": 100,
    "commission_on_fee": true,
    "label_name": "SmartCard Number",
    "amount": 20900
  },
  {
    "id": 295,
    "biller_code": "BIL121",
    "name": "DSTV Box Office bill",
    "default_commission": 0.3,
    "date_added": "2020-02-11T11:13:29.62Z",
    "country": "NG",
    "is_airtime": false,
    "biller_name": "DSTV BOX OFFICE",
    "item_code": "CB221",
    "short_name": "DSTV BOX OFFICE",
    "fee": 100,
    "commission_on_fee": true,
    "label_name": "SmartCard Number",
    "amount": 0
  },
  {
    "id": 296,
    "biller_code": "BIL122",
    "name": "GOTV LIGHT",
    "default_commission": 0.3,
    "date_added": "2020-02-11T11:13:29.62Z",
    "country": "NG",
    "is_airtime": false,
    "biller_name": "GOTV LIGHT",
    "item_code": "CB185",
    "short_name": "GOTV LIGHT",
    "fee": 100,
    "commission_on_fee": true,
    "label_name": "SmartCard Number",
    "amount": 410
  },
  {
    "id": 299,
    "biller_code": "BIL122",
    "name": "GOTV MAX",
    "default_commission": 0.3,
    "date_added": "2020-02-11T11:13:29.62Z",
    "country": "NG",
    "is_airtime": false,
    "biller_name": "GOTV MAX",
    "item_code": "CB188",
    "short_name": "GOTV MAX",
    "fee": 100,
    "commission_on_fee": true,
    "label_name": "SmartCard Number",
    "amount": 3600
  },
  {
    "id": 300,
    "biller_code": "BIL123",
    "name": "NOVA - One Day",
    "default_commission": 0.3,
    "date_added": "2020-02-11T11:13:29.62Z",
    "country": "NG",
    "is_airtime": false,
    "biller_name": "NOVA - One Day",
    "item_code": "CB189",
    "short_name": "NOVA - One Day",
    "fee": 100,
    "commission_on_fee": true,
    "label_name": "SmartCard Number",
    "amount": 60
  },
  {
    "id": 301,
    "biller_code": "BIL123",
    "name": "NOVA - One Week",
    "default_commission": 0.3,
    "date_added": "2020-02-11T11:13:29.62Z",
    "country": "NG",
    "is_airtime": false,
    "biller_name": "NOVA - One Week",
    "item_code": "CB190",
    "short_name": "NOVA - One Week",
    "fee": 100,
    "commission_on_fee": true,
    "label_name": "SmartCard Number",
    "amount": 300
  },
  {
    "id": 302,
    "biller_code": "BIL123",
    "name": "NOVA - One Month",
    "default_commission": 0.3,
    "date_added": "2020-02-11T11:13:29.62Z",
    "country": "NG",
    "is_airtime": false,
    "biller_name": "NOVA - One Month",
    "item_code": "CB191",
    "short_name": "NOVA - One Month",
    "fee": 100,
    "commission_on_fee": true,
    "label_name": "SmartCard Number",
    "amount": 900
  },
  {
    "id": 303,
    "biller_code": "BIL123",
    "name": "BASIC - One Day",
    "default_commission": 0.3,
    "date_added": "2020-02-11T11:13:29.62Z",
    "country": "NG",
    "is_airtime": false,
    "biller_name": "BASIC - One Day",
    "item_code": "CB192",
    "short_name": "BASIC - One Day",
    "fee": 100,
    "commission_on_fee": true,
    "label_name": "SmartCard Number",
    "amount": 90
  },
  {
    "id": 304,
    "biller_code": "BIL123",
    "name": "BASIC - One Week",
    "default_commission": 0.3,
    "date_added": "2020-02-11T11:13:29.62Z",
    "country": "NG",
    "is_airtime": false,
    "biller_name": "BASIC - One Week",
    "item_code": "CB193",
    "short_name": "BASIC - One Week",
    "fee": 100,
    "commission_on_fee": true,
    "label_name": "SmartCard Number",
    "amount": 450
  },
  {
    "id": 305,
    "biller_code": "BIL123",
    "name": "Startimes basic One Month",
    "default_commission": 0.3,
    "date_added": "2020-02-11T11:13:29.62Z",
    "country": "NG",
    "is_airtime": false,
    "biller_name": "BASIC - One Month",
    "item_code": "CB260",
    "short_name": "BASIC - One Month",
    "fee": 100,
    "commission_on_fee": true,
    "label_name": "SmartCard Number",
    "amount": 1300
  },
  {
    "id": 306,
    "biller_code": "BIL123",
    "name": "Startimes smart one day payment",
    "default_commission": 0.3,
    "date_added": "2020-02-11T11:13:29.62Z",
    "country": "NG",
    "is_airtime": false,
    "biller_name": "SMART - One Day",
    "item_code": "CB261",
    "short_name": "SMART - One Day",
    "fee": 100,
    "commission_on_fee": true,
    "label_name": "SmartCard Number",
    "amount": 120
  },
  {
    "id": 307,
    "biller_code": "BIL123",
    "name": "Startimes smart one week payment",
    "default_commission": 0.3,
    "date_added": "2020-02-11T11:13:29.62Z",
    "country": "NG",
    "is_airtime": false,
    "biller_name": "SMART - One Week",
    "item_code": "CB262",
    "short_name": "SMART - One Week",
    "fee": 100,
    "commission_on_fee": true,
    "label_name": "SmartCard Number",
    "amount": 600
  },
  {
    "id": 308,
    "biller_code": "BIL123",
    "name": "Startimes smart one month payment",
    "default_commission": 0.3,
    "date_added": "2020-02-11T11:13:29.62Z",
    "country": "NG",
    "is_airtime": false,
    "biller_name": "SMART - One Month",
    "item_code": "CB263",
    "short_name": "SMART - One Month",
    "fee": 100,
    "commission_on_fee": true,
    "label_name": "SmartCard Number",
    "amount": 1900
  },
  {
    "id": 309,
    "biller_code": "BIL123",
    "name": "Startimes classic one day payment",
    "default_commission": 0.3,
    "date_added": "2020-02-11T11:13:29.62Z",
    "country": "NG",
    "is_airtime": false,
    "biller_name": "CLASSIC - One Day",
    "item_code": "CB264",
    "short_name": "CLASSIC - One Day",
    "fee": 100,
    "commission_on_fee": true,
    "label_name": "SmartCard Number",
    "amount": 180
  },
  {
    "id": 310,
    "biller_code": "BIL123",
    "name": "Startimes classic one week payment",
    "default_commission": 0.3,
    "date_added": "2020-02-11T11:13:29.62Z",
    "country": "NG",
    "is_airtime": false,
    "biller_name": "CLASSIC - One Week",
    "item_code": "CB265",
    "short_name": "CLASSIC - One Week",
    "fee": 100,
    "commission_on_fee": true,
    "label_name": "SmartCard Number",
    "amount": 900
  },
  {
    "id": 311,
    "biller_code": "BIL123",
    "name": "Startimes classic one month payment",
    "default_commission": 0.3,
    "date_added": "2020-02-11T11:13:29.62Z",
    "country": "NG",
    "is_airtime": false,
    "biller_name": "CLASSIC - One month",
    "item_code": "CB266",
    "short_name": "CLASSIC - One month",
    "fee": 100,
    "commission_on_fee": true,
    "label_name": "SmartCard Number",
    "amount": 2600
  },
  {
    "id": 312,
    "biller_code": "BIL123",
    "name": "Startimes unique one day payment",
    "default_commission": 0.3,
    "date_added": "2020-02-11T11:13:29.62Z",
    "country": "NG",
    "is_airtime": false,
    "biller_name": "UNIQUE - One Day",
    "item_code": "CB267",
    "short_name": "UNIQUE - One Day",
    "fee": 100,
    "commission_on_fee": true,
    "label_name": "SmartCard Number",
    "amount": 240
  },
  {
    "id": 313,
    "biller_code": "BIL123",
    "name": "Startimes unique one week payment",
    "default_commission": 0.3,
    "date_added": "2020-02-11T11:13:29.62Z",
    "country": "NG",
    "is_airtime": false,
    "biller_name": "UNIQUE - One Week",
    "item_code": "CB268",
    "short_name": "UNIQUE - One Week",
    "fee": 100,
    "commission_on_fee": true,
    "label_name": "SmartCard Number",
    "amount": 1300
  },
  {
    "id": 314,
    "biller_code": "BIL123",
    "name": "Startimes unique one month payment",
    "default_commission": 0.3,
    "date_added": "2020-02-11T11:13:29.62Z",
    "country": "NG",
    "is_airtime": false,
    "biller_name": "UNIQUE - One Month",
    "item_code": "CB269",
    "short_name": "UNIQUE - One Month",
    "fee": 100,
    "commission_on_fee": true,
    "label_name": "SmartCard Number",
    "amount": 3800
  },
  {
    "id": 315,
    "biller_code": "BIL123",
    "name": "Startimes super one day payment",
    "default_commission": 0.3,
    "date_added": "2020-02-11T11:13:29.62Z",
    "country": "NG",
    "is_airtime": false,
    "biller_name": "SUPER - One Day",
    "item_code": "CB270",
    "short_name": "SUPER - One Day",
    "fee": 100,
    "commission_on_fee": true,
    "label_name": "SmartCard Number",
    "amount": 240
  },
  {
    "id": 316,
    "biller_code": "BIL123",
    "name": "Startimes super one week payment",
    "default_commission": 0.3,
    "date_added": "2020-02-11T11:13:29.62Z",
    "country": "NG",
    "is_airtime": false,
    "biller_name": "SUPER - One Week",
    "item_code": "CB271",
    "short_name": "SUPER - One Week",
    "fee": 100,
    "commission_on_fee": true,
    "label_name": "SmartCard Number",
    "amount": 1200
  },
  {
    "id": 317,
    "biller_code": "BIL123",
    "name": "Startimes super one month payment",
    "default_commission": 0.3,
    "date_added": "2020-02-11T11:13:29.62Z",
    "country": "NG",
    "is_airtime": false,
    "biller_name": "SUPER - One Month",
    "item_code": "CB272",
    "short_name": "SUPER - One Month",
    "fee": 100,
    "commission_on_fee": true,
    "label_name": "SmartCard Number",
    "amount": 3800
  },
  ]